### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#555]
# Required
- [x] New website with more clear unique selling point, download button that actually works and nicer per-language usage split
- [x] Extended documentation, integrate documentation into code base to keep up to date
- [x] CSV Reader Auto Detection @tdoehmen 
- [x] Parallelism @Mytherin 
- [x] Python Relation API
- [x] Miniparquet integration @hannesmuehleisen 
- [x] Miniparquet for Python & R APIs (& Shell?)

# Possible, but not critical
- [ ] Chunk collection buffer management
- [ ] Storage Updates (#49, #109)
- [ ] CTEs with other statement types (#160)
- [ ] Support explicit schema in column ref (#146)
- [x] Blob type (#72)
- [x] Decimal Type
- [ ] Set default schema that is used at runtime (#155)
- [ ] Add compatibility with several MySQL functions (#156)

**Comment by hawkfish** [comment]
I'm rather rusty but I could take a look at the function implementations if you give me a list. I'd also be happy to help with aggregate parallelism and CSV detection (both topics I have experience with).

**Comment by Mytherin** [comment]
Thank you for the offer! :) There are a number of things with which you could help us, if you are interested. Extending the aggregate hash table to support parallelism would be one that would be very helpful to us. The CSV reader is being worked on by @tdoehmen, perhaps if he needs some help on anything there he could respond. One thing that would be interesting for us as well would be automatic detection of DATE/TIMESTAMP formats; both for the CSV reader and for standard VARCHAR -> DATE/TIMESTAMP conversion.

**Comment by tdoehmen** [comment]
@Mytherin I intended to make use of the MonetDB conversion logic in src/common/types/time.cpp, src/common/types/date.cpp and src/common/types/timestamp.cpp. If we want a more comprehensive logic for detection, then it could make sense if someone takes on this part. @hawkfish I'm going for a first pull request for the CSV dialect/datatype detection this weekend. Let's see from there. Generally, suggestions / improvements are very welcome :)

**Comment by hawkfish** [comment]
One can [go overboard](https://research.tableau.com/sites/default/files/TR-2018-01.pdf) on time format detection, so a better approach IMHO is to add a `DATEPARSE` function of the kind we describe in that paper. If we have ICU (which would be useful for collation as well) that would make it pretty straightforward.

**Comment by Mytherin** [comment]
Very nice paper indeed :) I think adding a DATEPARSE function is indeed a great idea. Does ICU have support for automatic DATE detection? We kind of want to avoid including ICU unless really necessary, as it is such a large dependency. Although perhaps it is unavoidable in the end.

**Comment by hawkfish** [comment]
I've been looking at the PG `to-timestamp` and related functions and they are...complex. Not to mention written in C. If we want to implement them, we will have to copy the code and convert it to C++. We can also leverage block iteration to avoid searching the cache for the common case where the format argument is constant. But this has turned into a feature discussion and should maybe get moved to a new issue.  

Getting back to the putative release, do we have a list of functions we want?  I have not looked at the code in about nine months and would like to stick my toes back in the water slowly(!)

**Comment by Mytherin** [comment]
> I've been looking at the PG to-timestamp and related functions and they are...complex. Not to mention written in C. If we want to implement them, we will have to copy the code and convert it to C++. We can also leverage block iteration to avoid searching the cache for the common case where the format argument is constant. But this has turned into a feature discussion and should maybe get moved to a new issue.

We already have support for this in the REGEX function as well as sequence functions (i.e. if a regex is constant we only compile the regex once) - this should not be a problem to use in a function here as well. However, indeed, I think this function is likely very complex.

We have a list of functions in issue #193. You can have your pick there. Note that some functions are partially there already, for example we have `UPPER`, but no alias `UCASE` yet. Perhaps something like REPEAT, LTRIM/RTRIM, LPAD/RPAD or some of the bit operations? If a function that you are interested in implementing is not there or in the system feel free to suggest it as well :)

**Comment by hawkfish** [comment]
Do we have a checklist somewhere? I was going to look at some of the time functions, but they have been done.

**Comment by Mytherin** [comment]
The checklist is [here](https://github.com/cwida/duckdb/issues/193). Besides the checklist, in general most functions that are present in one of the other major OSS databases (PostgreSQL/MySQL/SQLite) we would like to implement as well (within reason of course). If there is a function missing there that you think would be relevant feel free to suggest it.

**Comment by hawkfish** [comment]
I'm just trying to avoid duplicating work. The list in that link is not one I can check off!

**Comment by Mytherin** [comment]
Ah, in that case it is sufficient to just announce you are going to work on a function in that thread :) We aren't that big of a team so accidental duplicate work is unlikely.
