### ISSUE TITLE
Index improvements

### ISSUE THREAD

**Issue by taniabogatsch** [duckdb/duckdb#5865]
This issue contains a list of further possible improvements to the ART/indexes in DuckDB. I will comment if I pick up work on any of these. Likewise, others are also welcome to do the same.

- [x] Disable sorting during `CREATE INDEX` for data distributions that consist mostly of duplicates and for string keys.
- [x] A `NodeChildIterator` or something similar to combine the `NextPos` and `NextPosAndByte` functions, as mentioned/discussed in #5812.
- [ ] No validity check for a key generation if `CREATE INDEX` because we filter `NULL`s before the index creation operation.
- [x] Move `expr->HasSideEffects()` in `plan_create_index.cpp` to also check children recursively (#5812)
- [x] Possibly memory managers for the nodes and the prefixes to further improve the allocation overhead of the many tiny allocations.
- [x] Other issues addressing the ART: #4967, #4891, #4886 (related to #1631), #4852, #5365

## Future Work

- [x] Move prefixes to separate prefix nodes
- [x] Inline row IDs directly into ART pointers if there is only one row ID in a leaf, #5365
- [x] Use shared memory during `Sink` to decrease the memory pressure of `CREATE INDEX`
- [x] Refactor (de)serialisation implementation to use the new buffers/fixed-size allocators
- [ ] Improve insertions, deletions, and constraint checking for bulk operations, which still use the 'old' code
- [ ] More key types
- [ ] Optional: parallel `combine` steps
- [ ] Optional: inline the `count` into the `Node` pointer, reducing the size of `Node16`, `Node48`, and `Node256` by one byte (due to alignment)

## Known Limitations

- [ ] [Over-Eager Unique Constraint Checking](https://duckdb.org/docs/sql/indexes#over-eager-unique-constraint-checking), #1631
- [ ] `INSERT OR IGNORE` - to-be-inserted-data is assumed to be `UNIQUE` #6500

**Comment by Tishj** [comment]
Should this not also be listed under the "Other issues addressing the ART" ?
https://github.com/duckdb/duckdb/issues/5365

**Comment by taniabogatsch** [comment]
Yes, fair point, I missed that!

**Comment by taniabogatsch** [comment]
> `ART::Insert(...)`: Maybe we want to wrap an insert operation in a class and use RAII? since it needs to clean up in case of failure

> We can keep this in mind, but I would not include it in this PR. Also, if we move to use the merge code for constraint checking before insertions, we no longer need to clean up anyways. I will move this to the ART improvements issue.

#5893

**Comment by taniabogatsch** [comment]
Currently, we null-terminate ART keys, like so:
```c++
template <>
void Key::CreateKey(ArenaAllocator &allocator, Key &key, string_t value) {
	key.len = value.GetSize() + 1;
	key.data = allocator.Allocate(key.len);
	memcpy(key.data, value.GetDataUnsafe(), key.len - 1);
	key.data[key.len - 1] = '\0';
}
```
This is a 'relic' from the original ART implementation and is required for ART traversal and merging ARTs (keys must not be subsets of each other). However, this design decision/requirement conflicts with null-terminated keys like this one:
```sql
CREATE TABLE t1 (c1 VARCHAR);
CREATE INDEX i0 ON t1 (c1);
INSERT INTO t1 VALUES (decode('g\x00'::BLOB)::VARCHAR),('g');
```
Because terminating the keys is required by ART traversal and merge operations, we cannot simply remove it but must rethink this if we want to support null-terminated keys like the one above. To fix the respective fuzzer issue, we will throw an exception for now.

**Comment by Tishj** [comment]
Hmm so null bytes play a vital role in the internals of the ART, and assume that no key originally contains a null byte?

Isn't there a way that we can differentiate between the original null byte and the artificial one by looking at the size?
Even `g\x00` will be extended to `g\x00\x00`, so only the null byte found at the `key.len-1` should be seen as terminating.

**Comment by Mytherin** [comment]
It is not a null-byte specifically, it is just that keys cannot be prefixes of each-other in the current ART setup. That is because a node can only be either an internal node or a leaf. If we have a prefix (e.g. `g\x00` and `g\x00\x00`) the `\x00` byte will both be a leaf (pointing to the first row) and a node (pointing to the second `\x00`). This is never a problem with fixed-size types, but can be a problem with strings and blobs - hence why the null-byte was chosen.

A fix for this would be to allow nodes to be both leafs and intermediate nodes at the same time - but I am not sure of the potential performance/memory usage implications of that. All ART algorithms will also have to be adjusted to account for the fact that values can be stored outside of the traditional leafs.

**Comment by tonyhb** [comment]
Using ULIDs as a PK and get errors with null terminated bytes - fixing that would be ideal (as would updates with indexes)

**Comment by taniabogatsch** [comment]
I am closing this issue as it does not relate to a specific bug and I will pick up remaining points in future ART PRs.
